{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file_005.Test_Credence_005 object at 0x000002A4D189D5D0>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_file_005.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "38e79673-a5a2-43e7-81b4-5fb3e1a8f284-attachment.txt", "type": "text/plain"}], "start": 1690747261231, "stop": 1690747261231, "uuid": "a7c358e6-2bee-4289-9211-0d59fc904806", "historyId": "3373f973f87d181b033c1208fbde30ae", "testCaseId": "3373f973f87d181b033c1208fbde30ae", "fullName": "test_file_005.Test_Credence_005#test_mul_004", "labels": [{"name": "suite", "value": "test_file_005"}, {"name": "subSuite", "value": "Test_Credence_005"}, {"name": "host", "value": "INBook_X1"}, {"name": "thread", "value": "7816-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file_005"}]}